# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-linter

on:
  [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24.0' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: |
        go get .

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
